[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure proper function routing
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing (optional, but good for future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {path = "!/.netlify/*"}
  conditions = {path = "!/api/*"}
  conditions = {path = "!/assets/*"}
  conditions = {path = "!/*.html"} 